
[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 16

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.75
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
