---
- name: All hosts up-to-date
  hosts: all
  become: true
  connection: local
  tasks:
    - name: Full system upgrade (yay)
      become: false
      kewlfft.aur.aur:
        upgrade: yes
        use: auto
        update_cache: yes

- import_playbook: playbooks/All/init.yml
