---
- name: All hosts up-to-date
  hosts: all
  become: true
  connection: local
  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: Full system upgrade (yay)
      become: false
      yay:
        update_cache: true
        upgrade: true

- import_playbook: playbooks/Jason/init.yml
- import_playbook: playbooks/Chester/init.yml
- import_playbook: playbooks/All/init.yml
