---
- name: All hosts up-to-date
  hosts: all
  become: true
  connection: local
  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

- name: Install apps
  hosts: all
  become: true
  connection: local
  tasks:
    - name: Install packackages
      yay:
        name:
          - spotify-launcher
          - keepassxc
          - neovim
          - alacritty 
          - visual-studio-code-bin
          - gdm-settings 
          - htop

- import_playbook: playbooks/Jason/init.yml
- import_playbook: playbooks/Chester/init.yml
- import_playbook: playbooks/All/init.yml