---
- name: Enable iommu for systemd
  hosts: Jason
  become: true
  connection: local
  tasks:
    - name: Find files that do not contain the word 'fallback'
      find:
        paths: "/efi/loader/entries"
        patterns: "*.conf"
        excludes: "*fallback*"
        recurse: yes
      register: result_files

    - name: Add 'intel_iommu=on iommu=pt' to options line
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^(options[^\n]*)(?<!intel_iommu=on iommu=pt)$'
        replace: '\1 intel_iommu=on iommu=pt'
      with_items: "{{ result_files.files }}"