---
- name: Setup Jason
  hosts: Jason
  become: true
  connection: local
  tasks:
    - name: Copy monitors file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/screenconfig/jason-monitors.xml"
        dest: "{{ lookup('env', 'HOME') }}/.config/monitors.xml"
        mode: '0644'