$orange = rgb(224, 125, 19)
$teal = rgba(0, 189, 156, 1)
$red = rgb(220, 57, 106)
$green = rgb(152, 195, 121)
$pink = rgb(218, 112, 214)
$yellow = rgb(230, 198, 47)

$foreground = rgba(242, 243, 244, 0.75)
$background = rgb(25, 19, 35)
$active_foreground = $yellow
$active_background = rgb(23, 20, 31)
$foreground_dark = $background

$badge_background_pink = $pink
$badge_background_teal = $teal
$badge_background_green = $green

$highlight = $yellow
