- name: Setup hyprland
  hosts: all
  connection: local
  tasks:
    - name: Install packages
      kewlfft.aur.aur: 
        name:
          - xdg-desktop-portal
          - xdg-desktop-portal-gtk
          - xdg-desktop-portal-hyprland
          - xdg-desktop-portal-wlr
          - wl-clipboard
    - name: Move desktop portal conf
      become: true
      copy:
        src: "etc/pipewire/pipewire-pulse.conf.d/switch-on-connect-device.conf"
        dest: "/etc/pipewire/pipewire-pulse.conf.d/switch-on-connect-device.conf"
        mode: "0644"

