---
- name: Setup mako
  hosts: all
  connection: local
  tasks:
    - name: install packages
      kewlfft.aur.aur: 
        name:
          - mako
    - name: Create mako dir
      file:
        path: "{{ lookup('env', 'HOME') }}/.config/mako/"
        state: directory
        owner: "{{ lookup('env', 'USER') }}"
    - name: Create mako dirs recursivly
      file:
        path: "{{ lookup('env', 'HOME') }}/.config/mako/{{ item.path }}"
        state: directory
        owner: "{{ lookup('env', 'USER') }}"
        mode: "{{ item.mode }}"
      with_filetree: mako/
      when: item.state == 'directory'
    - name: Move config files into place
      template:
        src: "{{ item.src }}"
        dest: "{{ lookup('env', 'HOME') }}/.config/mako/{{ item.path }}"
        force: yes
        owner: "{{ lookup('env', 'USER') }}"
      with_filetree: mako/
      when: item.state == 'file'
