---
- name: Setup sound
  hosts: all
  tasks:
    - name: Install packages
      kewlfft.aur.aur: 
        name:
          - pipewire
          - pipewire-docs
          - wireplumber
          - qpwgraph
          - pipewire-audio
          - pipewire-alsa
          - pipewire-pulse
          - pavucontrol
        state: latest
    - name: Move auto switch on connect conf
      become: true
      copy:
        src: "etc/xdg/xdg-desktop-portal/Hyprland-portals.conf"
        dest: "/etc/xdg/xdg-desktop-portal/Hyprland-portals.conf"
        mode: "0644"
