window:
  padding:
    x: 10
    y: 10
  decorations: none
  opacity: 0.95
  startup_mode: Maximized
  dynamic_title: true

font:
  normal:
    family: "CaskaydiaCove Nerd Font"
    style: Regular
  bold:
    family: "CaskaydiaCove Nerd Font"
    style: Bold
  italic:
    family: "CaskaydiaCove Nerd Font"
    style: Italic
  bold_italic:
    family: "CaskaydiaCove Nerd Font"
    style: "Bold Italic"
  
draw_bold_text_with_bright_colors: true

env:
  WINIT_X11_SCALE_FACTOR: "1"

key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }