---
- name: Install apps
  hosts: all
  become: true
  connection: local
  tasks:
    - name: Install packackages
      kewlfft.aur.aur:
        name:
          - spotify-launcher
          - keepassxc
          - visual-studio-code-bin
          - gdm-settings
          - htop
          - nvidia-settings
          - xclip
          - tmux
          - exa
          - obsidian
          - zoxide
