---
- name: Setup global bluetooth
  hosts: all
  become: yes
  tasks:
    - name: Install bluetooth
      kewlfft.aur.aur:
        name:
          - bluez
          - pulseaudio-bluez-utils
          - pulseaudio-bluetooth
    - name: Enable bluetooth
      systemd:
        name: bluetooth
        enabled: true
        state: started
