---
- name: Setup global bluetooth
  hosts: all
  become: yes
  tasks:
    - name: Install bluetooth
      pacman:
        name:
          - bluez
          - bluez-utils
        executable: yay
    - name: Enable bluetooth
      systemd:
        name: bluetooth
        enabled: true
        state: started
