---
- name: Setup global bluetooth
  hosts: all
  become: yes
  tasks:
    - name: Install bluetooth
      kewlfft.aur.aur:
        use: yay
        name:
          - bluez
          - bluez-utils
    - name: Enable bluetooth
      systemd:
        name: bluetooth
        enabled: true
        state: started
