---
- name: Setup zsh
  hosts: all
  tasks:
    - name: Copy .path
      copy:
        src: "_dot_path"
        dest: "{{ lookup('env', 'HOME') }}/.path"
        owner: "{{ lookup('env', 'USER') }}"
        mode: "0644"
