---
- name: Setup fonts
  hosts: all
  become: yes
  tasks:
    - name: Install fonts
      pacman:
        name:
          - ttf-cascadia-code-nerd
          - ttf-terminus-nerd
        executable: yay
