---
- name: Setup fonts
  hosts: all
  become: yes
  tasks:
    - name: Install fonts
      kewlfft.aur.aur:
        use: yay
        name:
          - ttf-cascadia-code-nerd
          - ttf-terminus-nerd
