---
- name: All hosts up-to-date
  hosts: all
  connection: local
  tasks:
    - name: Full system upgrade (yay)
      kewlfft.aur.aur:
        use: yay
        upgrade: yes
        update_cache: yes
