---
- name: Setup global git vars 
  hosts: all
  become: no
  tasks:
    - name: setup git name
      git_config:
        name: user.name
        scope: global
        value: "Steve"
    - name: setup git user email
      git_config:
        name: user.email
        scope: global
        value: stvbyr@users.noreply.github.com
