---
- name: Setup global git vars
  hosts: all
  become: no
  tasks:
    - name: Install git
      pacman:
        name:
          - git
          - git-delta
        executable: yay
    - name: Apply git configuration
      git_config:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        scope: global
      loop: "{{ config | dict2items }}" # https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#iterating-over-a-dictionary
      vars:
        config:
          user.name: sen-tou
          user.email: stvbyr@users.noreply.github.com
          add.interactive.useBuiltin: false # required for git 2.37.0
          core.excludesfile: ~/.gitignore.global
          core.pager: delta
          delta.alwaysnavigate: true # use n and N to move between diff sections
          delta.alwayslight: false # set to true if you're in a terminal w/ a light background color (e.g. the default macOS terminal)
          diff.colorMoved: default
          interactive.diffFilter: delta --color-only
          merge.conflictstyle: diff3
          include.path: ~/.gitconfig.local
    - name: Creating a file with content
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.gitignore.global"
        content: |
          Thumbs.db
          .idea
          .vscode
