---
- import_playbook: yay.yml
- import_playbook: full_system_upgrade.yml
- import_playbook: app.yml
- import_playbook: kitty.yml
- import_playbook: nvim.yml
- import_playbook: copy.yml
- import_playbook: git.yml
- import_playbook: php.yml
- import_playbook: python.yml
- import_playbook: rust.yml
- import_playbook: bluetooth.yml
- import_playbook: sound.yml
- import_playbook: fonts.yml
- import_playbook: zsh.yml
- import_playbook: docker.yml
- import_playbook: nas.yml
