---
- import_playbook: copy.yml
- import_playbook: git.yml
- import_playbook: rust.yml
- import_playbook: bluetooth.yml
- import_playbook: fonts.yml
- import_playbook: zsh.yml
- import_playbook: docker.yml
- import_playbook: steam.yml
  when: ansible_virtualization_role == "host"
- import_playbook: lutris.yml
  when: ansible_virtualization_role == "host"
- import_playbook: kvm.yml
  when: ansible_virtualization_role == "host"
- import_playbook: nas.yml