---
- import_playbook: copy.yml
- import_playbook: git.yml
- import_playbook: rust.yml
- import_playbook: bluetooth.yml
- import_playbook: fonts.yml
- import_playbook: zsh.yml
- import_playbook: steam.yml
- import_playbook: lutris.yml
- import_playbook: kvm.yml
- import_playbook: nas.yml