---
- name: Setup Kitty
  hosts: all
  vars:
    theme_folder: "{{ lookup('env', 'HOME') }}/.config/kitty/kitty-themes"
    theme: rose-pine/rose-pine.conf
  tasks:
    - name: Create kitty dirs recursivly
      file:
        path: "{{ lookup('env', 'HOME') }}/.config/kitty/{{ item.path }}"
        state: directory
        owner: "{{ lookup('env', 'USER') }}"
        mode: "{{ item.mode }}"
      with_filetree: kitty/
      when: item.state == 'directory'
    - name: Move config files into place
      template:
        src: "{{ item.src }}"
        dest: "{{ lookup('env', 'HOME') }}/.config/kitty/{{ item.path }}"
        force: yes
        owner: "{{ lookup('env', 'USER') }}"
      with_filetree: kitty/
      when: item.state == 'file'
- name: Install Kitty
  hosts: all
  become: true
  connection: local
  tasks:
    - name: Install packackages
      pacman:
        executable: yay
        name:
          - kitty
    - name: remove packackages
      pacman:
        executable: yay
        name:
          - alacritty
          - gnome-terminal
        state: removed
