---
# git clone --depth 1 https://github.com/wbthomason/packer.nvim
- name: Setup Nvim
  hosts: all
  tasks:
    - name: ensures {{ lookup('env', 'HOME') }}/.config/nvim dir exists
      file:
        path: "{{ lookup('env', 'HOME') }}/.config/nvim"
        state: directory

- name: Install apps
  hosts: all
  become: true
  connection: local
  tasks:
    - name: Install packackages
      kewlfft.aur.aur: 
        name:
          - neovim
          - xdg-desktop-portal
