---
# git clone --depth 1 https://github.com/wbthomason/packer.nvim
- name: Setup Nvim
  hosts: all
  connection: local
  tasks:
    - name: Install packackages
      kewlfft.aur.aur: 
        use: yay
        name:
          - neovim
          - ripgrep
          
