---
- name: setup python
  hosts: all
  connection: local
  tasks:
    - name: Install python
      kewlfft.aur.aur: 
        use: yay
        name:
          - python
          - python-pip
          - python-pynvim
