---
- name: Setup rust
  hosts: all
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  connection: local
  tasks:
    - name: Install rust
      kewlfft.aur.aur:
        use: yay
        name:
          - rust

