---
- name: Setup rust
  hosts: all
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  connection: local
  # source: https://waylonwalker.com/install-rust/
  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes
    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0777'
        force: 'yes'
      tags:
        - rust
    - name: install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust
    - name: update rust
      shell: rustup update
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.zfunc/"
        owner: "{{ lookup('env', 'USER') }}"
        state: directory
        mode: '0755'
    - name: setup completions
      become: false
      shell: "rustup completions zsh > {{ lookup('env', 'HOME') }}/.zfunc/_rustup"
    
    