---
- name: Setup zsh
  hosts: all
  become: yes
  tasks:
    - name: Install zsh
      pacman:
        name:
          - zsh
          - starship
        executable: yay
    - name: Change default shell to zsh
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /usr/bin/zsh
    - name: Copy .zshrc
      copy:
        src: "_dot_zshrc"
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"
        owner: "{{ lookup('env', 'USER') }}"
        mode: "0644"
